import { ReactElement, useContext, useState, useCallback } from 'react';
import { StyleSheet, View } from 'react-native';
import { BottomTabNavigationProp } from '@react-navigation/bottom-tabs';
import { useFocusEffect } from '@react-navigation/native';

import {
  ManageJourneyRouteProp,
  BottomTabsParamList,
  JourneyValues,
  ColorScheme,
  Icons,
} from '../models';
import { JourneyContext } from '../store/journey-context';
import JourneyForm from '../components/ManageJourney/JourneyForm';
import Button from '../components/UI/Button';
import IconButton from '../components/UI/IconButton';
import { GlobalStyles } from '../constants/styles';

interface ManageJourneyProps {
  route: ManageJourneyRouteProp;
  navigation: BottomTabNavigationProp<BottomTabsParamList, 'ManageJourney'>;
}

const ManageJourney: React.FC<ManageJourneyProps> = ({
  route,
  navigation,
}): ReactElement => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const journeyCtx = useContext(JourneyContext);
  const editedJourneyId = route.params?.journeyId;
  let isEditing = !!editedJourneyId;

  const selectedJourney = journeyCtx.journeys.find(
    (journey) => journey.id === editedJourneyId
  );

  // Empty, when no default values provided
  const [journeyValues, setJourneyValues] = useState<JourneyValues>({
    name: selectedJourney?.name || '',
    description: selectedJourney?.description || '',
    scheduled_start_time: selectedJourney?.scheduled_start_time || null,
    scheduled_end_time: selectedJourney?.scheduled_end_time || null,
    available_money: selectedJourney?.costs.available_money || 0,
    planned_costs: selectedJourney?.costs.planned_costs || 0,
    countries: selectedJourney?.countries || [],
  });

  useFocusEffect(
    useCallback(() => {
      // JourneyValues set, when screen is focused
      setJourneyValues({
        name: selectedJourney?.name || '',
        description: selectedJourney?.description || '',
        scheduled_start_time: selectedJourney?.scheduled_start_time || null,
        scheduled_end_time: selectedJourney?.scheduled_end_time || null,
        available_money: selectedJourney?.costs.available_money || 0,
        planned_costs: selectedJourney?.costs.planned_costs || 0,
        countries: selectedJourney?.countries || [],
      });

      return () => {
        // Clean up function, when screen is unfocused
        // reset JourneyValues
        setJourneyValues({
          name: '',
          description: '',
          scheduled_start_time: null,
          scheduled_end_time: null,
          available_money: 0,
          planned_costs: 0,
          countries: [],
        });
        // reset journeyId in navigation params for BottomTab
        navigation.setParams({ journeyId: undefined });
      };
    }, [])
  );

  // async function deleteJourneyHandler() {
  //   setisSubmitting(true);
  //   try {
  //     await deleteExpense(editedExpenseId);
  //     expenseCtx.deleteExpense(editedExpenseId);
  //     navigation.goBack();
  //   } catch (error) {
  //     setError("Could not delete expense!");
  //     setisSubmitting(false);
  //   }
  // }

  function cancelHandler() {
    navigation.goBack();
  }

  // async function confirmHandler(expenseData) {
  //   setisSubmitting(true);
  //   try {
  //     if (isEditing) {
  //       // Optimistic Updating
  //       expenseCtx.updateExpense(editedExpenseId, expenseData);
  //       await updateExpense(editedExpenseId, expenseData);
  //     } else {
  //       const id = await storeExpense(expenseData);
  //       expenseCtx.addExpense({ ...expenseData, id: id }); // id generated by firebase will be passed to the context aswell
  //     }
  //     navigation.goBack();
  //   } catch (error) {
  //     setError("Could not safe data - please try again later!");
  //     setisSubmitting(false);
  //   }
  // }

  return (
    <View>
      <JourneyForm
        onCancel={cancelHandler}
        onSubmit={() => {}}
        submitButtonLabel={isEditing ? 'Update' : 'Add'}
        defaultValues={isEditing ? journeyValues : undefined}
      />
      <View style={styles.btnContainer}>
        <IconButton
          icon={Icons.delete}
          color={GlobalStyles.colors.error200}
          onPress={() => {}}
          size={36}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  btnContainer: {
    alignItems: 'center',
    marginTop: 18,
  },
});

export default ManageJourney;
