import { MinorStage, Accommodation, PlaceToVisit } from '../models';

export const MINORSTAGES: MinorStage[] = [
  {
    id: 1,
    title: 'Minor Stage 1',
    country: 'Germany',
    baseLocation: {
      name: 'Hotel 1',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 1',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 1',
        costs: 100,
        booked: false,
        place: 'Place 1',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-09'),
    scheduled_end_time: new Date('2025-01-10'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
  {
    id: 2,
    title: 'Minor Stage 2',
    country: 'France',
    baseLocation: {
      name: 'Hotel 2',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 2',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 2',
        costs: 100,
        booked: false,
        place: 'Place 2',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-10'),
    scheduled_end_time: new Date('2025-01-11'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
  {
    id: 3,
    title: 'Minor Stage 3',
    country: 'Spain',
    baseLocation: {
      name: 'Hotel 3',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 3',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 3',
        costs: 100,
        booked: false,
        place: 'Place 3',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-11'),
    scheduled_end_time: new Date('2025-01-12'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
  {
    id: 4,
    title: 'Minor Stage 4',
    country: 'Italy',
    baseLocation: {
      name: 'Hotel 4',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 4',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 4',
        costs: 100,
        booked: false,
        place: 'Place 4',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-12'),
    scheduled_end_time: new Date('2025-01-13'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
  {
    id: 5,
    title: 'Minor Stage 5',
    country: 'Greece',
    baseLocation: {
      name: 'Hotel 5',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 5',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 5',
        costs: 100,
        booked: false,
        place: 'Place 5',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-13'),
    scheduled_end_time: new Date('2025-01-14'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
  {
    id: 6,
    title: 'Minor Stage 6',
    country: 'Portugal',
    baseLocation: {
      name: 'Hotel 6',
      description: 'A nice hotel',
      coordinates: { lat: 1, lon: 1 },
      costs: 100,
      booked: false,
      link: 'https://www.google.com',
    },
    placesToVisit: [
      {
        name: 'Place 6',
        description: 'A nice place',
        coordinates: { lat: 1, lon: 1 },
        visited: false,
        favorite: false,
        link: 'https://www.google.com',
      },
    ],
    activities: [
      {
        description: 'Activity 6',
        costs: 100,
        booked: false,
        place: 'Place 6',
        link: 'https://www.google.com',
      },
    ],
    done: false,
    scheduled_start_time: new Date('2025-01-14'),
    scheduled_end_time: new Date('2025-01-15'),
    costs: {
      available_money: 20000,
      planned_costs: 10000,
      money_exceeded: false,
    },
  },
];
